import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import SharedLayout from "@/components/SharedLayout";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "PortFolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <SharedLayout>
          {children}
        </SharedLayout>
      </body>
    </html>
  );
}
